### PR TITLE
[Discussion] TodoWithNoRequestDelegate

### PR DESCRIPTION
**Pull request by Carl-Hugo**
- Extract the `Service` into its own class to limit `TodoApi`'s responsibilities
    - I created the `Service` class as a nested class if, for some reason, you wanted to show possibilities of partial classes. It could also be renamed `TodoApiService` and moved to `TodoApiService.cs`, making the file discovery easier (VS nest `TodoApi.*.cs` under `TodoApi.cs` and collapse the file tree by default). I like nested classes to keep a "feature/unit" together.
- Use of constructor injection. 
    - Constructor injection should always be the preferred method, then, if impossible go-to method injection, then property injection. 
    - This has many advantages, starting by guarding against `null` in one place instead of *N* (i.e., required dependencies).
- Move object composition to composition root, getting service locator out of the `TodoApi`.
    - I understand that it needs to happen somewhere, and I way prefer at the framework level. Still, if that needs to occur in the application code, the composition root is a better place than spread across files in an application.
    - I think this should improve maintainability (no app stay small for long; I understand that this is a minimalist sample, but thinking real-life here)
    - Which opens the following question: why is the framework not supporting this use-case, out of the box? We should not need to wire up DI manually when using built-in features. Think about how easy it would be to create a Web API if we could define an endpoint that points to an arbitrary method somewhere with DI, all wired up by the framework! BTW I never thought of that before; your experiment lead me to this conclusion (but now I want that!).

### CODE REVIEW

**Comment by davidfowl** [comment]
Same feedback as https://github.com/davidfowl/Todos/pull/8. I would do something like this in a new sample and I wouldn't over genericize it.

> I created the Service class as a nested class if, for some reason, you wanted to show possibilities of partial classes. It could also be renamed TodoApiService and moved to TodoApiService.cs, making the file discovery easier (VS nest TodoApi.*.cs under TodoApi.cs and collapse the file tree by default). I like nested classes to keep a "feature/unit" together.

Seems fine, I would move it to another sample that splits the "service" and API.

> Constructor injection should always be the preferred method, then, if impossible go-to method injection, then property injection.

Method injection is the original dependency injection, the constructor is a method 😉. Anyways having another sample with a class based approach is preferred to changing the existing methods.

> Move object composition to composition root, getting service locator out of the TodoApi.

This is the fun one. 

> I understand that it needs to happen somewhere, and I way prefer at the framework level. Still, if that needs to occur in the application code, the composition root is a better place than spread across files in an application.

Not exactly. 

> I think this should improve maintainability (no app stay small for long; I understand that this is a minimalist sample, but thinking real-life here)

This can be written in a generic way but the point of this example is to show how all of the pieces work without obfuscation.

> Which opens the following question: why is the framework not supporting this use-case, out of the box? We should not need to wire up DI manually when using built-in features. Think about how easy it would be to create a Web API if we could define an endpoint that points to an arbitrary method somewhere with DI, all wired up by the framework! BTW I never thought of that before; your experiment lead me to this conclusion (but now I want that!).

Like MVC controllers and actions?

**Comment by Carl-Hugo** [comment]
> Like MVC controllers and actions?

Yes, but endpoint/routing directly, like `app.MapGet("/api/todos", some way to register your method/handler/whatnot);`. Brainstorming here, something like `app.MapGet<GetAllTodoHandler>("/api/todos")`? That would be even better than a controller/actions, don't you think?

> > Move object composition to composition root, getting service locator out of the TodoApi.
> 
> This is the fun one.

Ok, genuine question, what is fun about centralizing objects composition in the composition root versus spreading it out in your application? 

My understanding of DI/IoC is that you want to take the dependency control away for the class using them. Doing so makes it easier to control your program from its entry point without the need to open multiple files here and there when you want to change something (i.e., Open/Closed).
In my experience that helps bring flexibility to the mix, with very limited efforts/cost.

> Method injection is the original dependency injection, the constructor is a method 😉. 

The constructor is a method indeed, but it is a special method, that gets called only once per instance. Constructor injection usually means using "required dependencies", while method/property injection often lead to "optional dependencies" (especially property injection).

I don't know about "original dependency injection", but old things are not always good to keep, that's why there is a thing called evolution :stuck_out_tongue_winking_eye:

Seriously, we can have different opinions, I'm not looking to find the ultimate right or wrong, I'm only discussing here, and I'd like to know your point of view; maybe that will make mine change/evolve.

> Anyways having another sample with a class based approach is preferred to changing the existing methods.

Make sense; I only opened those PRs to discuss a few things, as I told you on Twitter. I was not expecting you to merge them. 

That said, if you want help creating new samples, feel free to tell me what you want, and I'll do my best to help you out.

**Comment by davidfowl** [comment]
> Yes, but endpoint/routing directly, like app.MapGet("/api/todos", some way to register your method/handler/whatnot);. Brainstorming here, something like app.MapGet<GetAllTodoHandler>("/api/todos")? That would be even better than a controller/actions, don't you think?

I think generics like that are ugly honestly. It would also require adding overloads to Map* methods and it would be limited to services. What if I wanted to inject parsed route parameters or query string args or form fields? The ability to declare how the argument are bound is a better model, I’m still looking for ways to do this with endpoint routing (I have several experiments).

> Ok, genuine question, what is fun about centralizing objects composition in the composition root versus spreading it out in your application?

Doesn’t matter where it is. As long as it’s per whatever is being instantiated. What you have is clean but as a teaching tool I think it’s important for people to understand that the “service locator pattern” isn’t really an issue if you’re at the composition root of something. It doesn’t even need to be in a single place it just needs to be done at the right place.

Great discussion thanks for the PRs

**Comment by Carl-Hugo** [comment]
> The ability to declare how the argument are bound is a better model, [...]

True, I like explicitness (if that's a word)...

> [...] I’m still looking for ways to do this with endpoint routing (I have several experiments).

Are these on GitHub? I'm curious now

**Comment by davidfowl** [comment]
https://github.com/davidfowl/uController

**Pull request closed without merging**
