### PR TITLE
added dockerfiles + dockercompose

### PR DESCRIPTION
**Pull request by musinit**

### CODE REVIEW

**Comment by davidfowl** [comment]
Leave out the compose file. I’m not sure what the point of running all together is.

**Comment by musinit** [comment]
Sure

**Comment by davidfowl** [comment]
Why are these docker files all in the root of the repository?

**Comment by musinit** [comment]
I wanted somehow to reuse nuget.config for all these dockerfiles. If I move all them into subdirectories, I could now copy nuget.config, because it will be out of build context and I would need to copy nuget.config in all subdirectories.

**Comment by bplasmeijer** [comment]
@musinit Please move docker files into the project folders, see https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

**Comment by bradwilson** [comment]
Are these Dockerfiles intended to be used iteratively during development? If so, then you'll probably want to follow the best practice for .NET Core + Docker of separating restore and build, since NuGet restore is the by-far most expensive part of the process (and forcing a re-run of the restore is punishing).

Example:

```dockerfile
### Build container
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env

WORKDIR /app

# Restore
COPY ./TodoBasic/*.csproj ./
RUN dotnet restore

# Build & publish
COPY ./TodoBasic ./
RUN dotnet publish -c Release -o out

### Runtime container
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1

WORKDIR /app

COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "Todos.dll"]
```

**Comment by Carl-Hugo** [comment]
If you want to reuse files, you could create a base image, copy everything in it, `dotnet build` all projects, then `dotnet publish` based on that base-image in the other dockerfile (using the no-build flag to save time). 

That said, this may add too much complexity for what I understand of this project. I'm leaving you the comment so you or someone else could use this technique in another project...

**Comment by musinit** [comment]
Thanks!

**Pull request closed without merging**
